//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TESTEntities : DbContext
    {
        public TESTEntities()
            : base("name=TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Копия_user_import> Копия_user_import { get; set; }
        public virtual DbSet<Копия_Заказ_import> Копия_Заказ_import { get; set; }
        public virtual DbSet<Копия_Пункты_выдачи_import> Копия_Пункты_выдачи_import { get; set; }
        public virtual DbSet<Копия_Товар_import_Посуда> Копия_Товар_import_Посуда { get; set; }

        private static TESTEntities _context;

        public static TESTEntities GetContext()
        {
            if (_context == null)
            {
                _context = new TESTEntities();
            }
            return _context;
        }
    }
}
