//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Windows.Media.Media3D;

    public partial class Копия_Товар_import_Посуда
    {
        public int Id { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<short> Стоимость { get; set; }
        public Nullable<byte> Размер_максимально_возможной_скидки { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public string Категория_товара { get; set; }
        public Nullable<byte> Действующая_скидка { get; set; }
        public Nullable<byte> Кол_во_на_складе { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        
        public string PhotoFull
        {
            get
            {
                if (this.Изображение == null)
                {
                    return null;
                }
                else
                {
                    string namePhoto = Directory.GetCurrentDirectory() + "\\Photo\\" + Изображение;
                    return namePhoto;
                }
            }
        }
    }
}
