//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Копия_Пункты_выдачи_import
    {
        public int Id { get; set; }
        public Nullable<int> column1 { get; set; }
        public string column2 { get; set; }
        public string column3 { get; set; }
        public Nullable<byte> column4 { get; set; }
    }
}
