//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Копия_Заказ_import
    {
        public int Id { get; set; }
        public Nullable<int> Номер_заказа { get; set; }
        public string Состав_заказа { get; set; }
        public Nullable<int> Дата_заказа { get; set; }
        public Nullable<int> Дата_доставки { get; set; }
        public Nullable<byte> Пункт_выдачи { get; set; }
        public string ФИО_клиента { get; set; }
        public Nullable<short> Код_для_получения { get; set; }
        public string Статус_заказа { get; set; }
        public string column9 { get; set; }
        public string column10 { get; set; }
        public string column11 { get; set; }
        public string column12 { get; set; }
    }
}
